cacheFolder: .yarn/cache

enableGlobalCache: false

nodeLinker: node-modules

npmScopes:
  toss-design-system:
    npmAlwaysAuth: true
    npmAuthToken: NPM_TOKEN
    npmRegistryServer: "https://registry.npmjs.org"
